[book]
authors = ["erri120"]
language = "en"
multilingual = false
src = "src"
title = "NextModInstaller - Docs"

[build]
create-missing = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js"]
git-repository-url = "https://github.com/erri120/NextModInstaller"
edit-url-template = "https://github.com/erri120/NextModInstaller/edit/main/docs/{path}"

[output.html.print]
enable = false
