name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "docs/**/*"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/**"
      - "docs/**/*"
  workflow_dispatch:

env:
  MDBOOK_VERSION: "0.4.32"
  MDBOOK_MERMAID_VERSION: "0.12.6"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ env.MDBOOK_VERSION }}-${{ env.MDBOOK_MERMAID_VERSION }}

      - name: Install dependencies
        run: |
          cargo install --version ${{ env.MDBOOK_VERSION }} mdbook
          cargo install --version ${{ env.MDBOOK_MERMAID_VERSION }} mdbook-mermaid

      - name: Build
        working-directory: docs
        run: mdbook build

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: "github-pages"
          path: "docs/book"

  gh-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ build ]

    concurrency:
      group: "pages"
      cancel-in-progress: false

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: "github-pages"
